name: Build & Deploy .NET Backend Docker

# Trigger the workflow when code is pushed to main final
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ShoppingCartAPI/ShoppingCart

      # 4️⃣ Build and publish
      - name: Build and publish
        run: dotnet publish -c Release -o out
        working-directory: ShoppingCartAPI/ShoppingCart

      # 5️⃣ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest .
        working-directory: ShoppingCartAPI/ShoppingCart

      # 7️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to backend EC2 via Bastion
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PRIVATE_IP }} # Backend EC2 PRIVATE IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          # Bastion (Jump Host)
          proxy_host: ${{ secrets.EC2_BASTION_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          proxy_port: 22

          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest

            docker stop dotnet-backend || true
            docker rm dotnet-backend || true

            docker run -d --name dotnet-backend \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -p 5000:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest
